#!/bin/bash

# Start MedExpertMatch service remotely on 192.168.0.73 with local profile
# This script provides commands to run manually on the remote server

REMOTE_HOST="192.168.0.73"
REMOTE_USER="berdachuk"
PROJECT_PATH="/home/berdachuk/projects-ai/expert-match-root/med-expert-match"
PROFILE="local"
LOG_FILE="${PROJECT_PATH}/logs/med-expert-match.log"
SERVICE_PORT="8094"

echo "=========================================="
echo "MedExpertMatch Remote Service Starter"
echo "=========================================="
echo ""
echo "Remote Host: ${REMOTE_HOST}"
echo "Project Path: ${PROJECT_PATH}"
echo "Profile: ${PROFILE}"
echo "Port: ${SERVICE_PORT}"
echo ""
echo "To start the service, SSH into the remote server and run:"
echo ""
echo "ssh ${REMOTE_USER}@${REMOTE_HOST}"
echo ""
echo "Then execute these commands:"
echo ""
echo "cd ${PROJECT_PATH}"
echo "mkdir -p logs"
echo "nohup mvn spring-boot:run -Dspring-boot.run.arguments=\"--spring.profiles.active=${PROFILE}\" > ${LOG_FILE} 2>&1 &"
echo ""
echo "Or use this one-liner:"
echo ""
echo "ssh ${REMOTE_USER}@${REMOTE_HOST} 'cd ${PROJECT_PATH} && mkdir -p logs && nohup mvn spring-boot:run -Dspring-boot.run.arguments=\"--spring.profiles.active=${PROFILE}\" > ${LOG_FILE} 2>&1 &'"
echo ""
echo "After starting, check health with:"
echo "curl http://${REMOTE_HOST}:${SERVICE_PORT}/actuator/health"
echo ""
echo "View logs with:"
echo "ssh ${REMOTE_USER}@${REMOTE_HOST} 'tail -f ${LOG_FILE}'"
echo ""
